/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 78fd4c407d0f154e886f142d6d31c732)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	APP_ORIGIN?: "https://crestix-ai-staging.survey-system.workers.dev";
	TOKEN_ENCRYPTION_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		APP_ORIGIN: "https://crestix-ai-staging.survey-system.workers.dev";
		TOKEN_ENCRYPTION_KEY: string;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ORIGIN" | "TOKEN_ENCRYPTION_KEY">> {}
}
